### ISSUE TITLE
Doesn't work with update 8?

### ISSUE THREAD

**Issue by iamdrscott** [SimonvBez/SatisfactoryTrainRearranger#2]
Very sad, I have wanted this capability for a while.  This is what I get, using the EXE, following the instructions.  Is it me, or the tool?

Decompressing...Traceback (most recent call last):
  File "train_rearranger.py", line 812, in <module>
  File "train_rearranger.py", line 689, in main
  File "train_rearranger.py", line 524, in __init__
  File "train_rearranger.py", line 557, in unzip_body
zlib.error: Error -3 while decompressing data: unknown compression method

**Comment by SimonvBez** [comment]
Hi! Thanks for bringing this up.
I haven't tested the tool on Update 8 yet, so I'm not surprised that something is going wrong.
To assist me, could you upload your savefile and tell me if you're using any mods?
I'll try to take a closer look at it somewhere this week!

**Comment by SimonvBez** [comment]
I've started working on it today, no need for a save file anymore. Update 8 introduced a whole bunch of changes to the save format.
Current progress is that I got the parsing working, so it's reading all the Stations and Trains correctly. I will continue tomorrow with writing the new save file.

**Comment by SimonvBez** [comment]
Code has been fully updated to work with the latest version of Satisfactory (as of now v0.8.3.1) and a new v0.2.0 Release of this tool has been made
